<a href="https://colab.research.google.com/github/it-ces/PUBLIC-AI/blob/main/OPTIMIZATION/Genetic_Linear_Regression_(BIT).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Genetic linear regression improved with Simulated annealing!

In [ ]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [ ]:
import random
import numpy as np
import pandas as pd
import math
from numpy import exp
import matplotlib.pyplot as plt
from numpy.random import randn
from numpy import asarray

In [ ]:
A,b = np.array([1,2,3]) , np.array([4,12,3])
A@A

14

Matrix multiplication:

```python
A @ A  
```
is equal to:

\begin{equation}
\sum_{i=1}^{n} a_{i}^{2}
\end{equation}

In [ ]:
A@b

37

In [ ]:
X = np.array([[4,1,0], [6,3,2], [1,1,0]])
D = np.array([[1,2,3],  [0,0,1], [2,1,0]])

# Matrix multiplication

$$
\begin{pmatrix}
4 & 1 & 0 \\
6 & 3 & 2 \\
1 & 1 & 0
\end{pmatrix}
\begin{pmatrix}
1 & 2 & 3 \\
0 & 0 & 1 \\
2 & 1 & 0
\end{pmatrix}
=
\begin{pmatrix}
4 & 8 & 13 \\
10 & 14  & 21 \\
1 & 2 & 4
\end{pmatrix}
$$

In [ ]:
X@D

array([[ 4,  8, 13],
       [10, 14, 21],
       [ 1,  2,  4]])

In [ ]:
# Create the database with multiplications....
def linear(betas, X):
  return X@betas

In [ ]:
b1,b2,b3,b4 = 45.5 , 3.5, 7.8, 8.98,

In [ ]:
data = np.array([[ 1,3,4,5]])
betas = np.array([b1,b2,b3,b4])
data@betas

array([132.1])

In [ ]:
samples = 341
data = [
    [random.uniform(14, 88),
     random.randint(1,33), random.gauss(10, 3.4),
     random.gauss(50,12)] for _ in range(samples)]

In [ ]:
y = []
for pattern in data:
  y.append((np.array(pattern) @ betas) + random.gauss(0,1.4)) # Here add a normal error with 0, cosntant variance

In [ ]:
# Stack in database
df  =  pd.DataFrame(data, columns=['x1', 'x2', 'x3', 'x4'])
df['y'] = y
# We need add a columns of 1 to calculate B0
df['x0']  = 1

In [ ]:
df

x1  x2         x3         x4            y  x0
0    15.176279  13   5.743380  49.819760  1226.621678   1
1    29.627862  18   3.641718  56.578389  1948.037118   1
2    18.627144  27   7.928655  64.322218  1585.372687   1
3    52.554207  29  10.846921  49.172270  3020.621257   1
4    20.551601   3  12.528378  54.718358  1533.210346   1
..         ...  ..        ...        ...          ...  ..
336  50.768823   4   8.359166  49.709597  2836.584307   1
337  16.843095  16  14.907006  58.258795  1460.005737   1
338  42.346361   1   5.092311  65.541362  2560.122142   1
339  27.476889  29  12.327338  59.734367  1984.866353   1
340  44.458097  28   6.129592  39.505962  2520.730706   1

[341 rows x 6 columns]

In [ ]:
betas_i = [3,4,5,1]

In [ ]:
df.loc[:, ['x1', 'x2', 'x3', 'x4']] @ betas_i

0      176.065501
1      235.670564
2      267.846927
3      377.069494
4      191.015050
          ...    
336    259.811899
337    247.323110
338    222.042001
339    319.801723
340    315.528212
Length: 341, dtype: float64

In [ ]:
X = [ 'x1', 'x2', 'x3', 'x4']

In [ ]:
df

x1  x2         x3         x4            y  x0
0    15.176279  13   5.743380  49.819760  1226.621678   1
1    29.627862  18   3.641718  56.578389  1948.037118   1
2    18.627144  27   7.928655  64.322218  1585.372687   1
3    52.554207  29  10.846921  49.172270  3020.621257   1
4    20.551601   3  12.528378  54.718358  1533.210346   1
..         ...  ..        ...        ...          ...  ..
336  50.768823   4   8.359166  49.709597  2836.584307   1
337  16.843095  16  14.907006  58.258795  1460.005737   1
338  42.346361   1   5.092311  65.541362  2560.122142   1
339  27.476889  29  12.327338  59.734367  1984.866353   1
340  44.458097  28   6.129592  39.505962  2520.730706   1

[341 rows x 6 columns]

# MSE

\begin{equation}
\frac{1}{n} \sum_{i=1}^{n} (y_{i} - \hat{y}_{i})^{2}
\end{equation}






# R-square

$$
SS_{res} = \sum (y_{i} - \hat{y})^{2}
$$

$$
SS_{tot} = \sum (y_{i} - \bar{y})^{2}
$$

$$
R = 1 - \frac{SS_{res}}{SS_{tot}}
$$







In [ ]:
def Rsquare(y, ypred):
  SSres = (y - ypred) @ (y - ypred)
  SStot =  (y - np.mean(y)) @ (y - np.mean(y))
  return 1 - (SSres/SStot)

def RMSE(y, ypred):
  return ((y - ypred) @ (y - ypred))/df.shape[0],

def fitnessFun(chromosome, X, target, df, metric='RMS'):
  yhat =  df.loc[:,X] @  chromosome
  y = df.loc[:,target]
  if metric == 'R':
    return Rsquare(y, yhat),
  else:
    return RMSE(y, yhat)

In [ ]:
fitnessFun(betas_i, X, 'y', df)

(7617123.683744492,)

In [ ]:
!pip install deap > null

In [ ]:
import random
from deap import base
from deap import creator
from deap import tools
from deap import algorithms

In [ ]:
## See the box a while

In [ ]:
creator.create("FitnessMax", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)
toolbox = base.Toolbox()
# Attribute generator
toolbox.register("geneNormal", random.gauss, 0, 10)
# Structure initializers
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.geneNormal, len(X))
toolbox.register("population", tools.initRepeat, list, toolbox.individual)
toolbox.register("evaluate", lambda chromosome: fitnessFun(chromosome=chromosome, X=X, target='y', df=df ))
toolbox.register("mate", tools.cxOnePoint)
toolbox.register("mutate", tools.mutGaussian, mu=0, sigma=10 , indpb=0.1)
toolbox.register("select", tools.selTournament, tournsize=10)


def main():
    pop = toolbox.population(n=250)
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("avg", np.mean)
    stats.register("std", np.std)
    stats.register("min", np.min)
    stats.register("max", np.max)

    pop, log = algorithms.eaSimple(pop, toolbox, cxpb=0.99, mutpb=0.15, ngen=200,
                                   stats=stats, halloffame=hof, verbose=True)
    return hof, log
best, log = main()
best[0].fitness

gen	nevals	avg        	std        	min        	max        
0  	250   	1.03103e+07	4.65741e+06	1.58522e+06	2.76143e+07
1  	246   	4.66674e+06	2.64481e+06	503160     	1.61912e+07
2  	248   	1.60153e+06	1.04199e+06	356172     	5.35623e+06
3  	250   	544729     	267065     	324084     	2.38075e+06
4  	247   	378622     	84524.7    	324084     	1.42104e+06
5  	246   	354790     	129854     	322497     	2.34528e+06
6  	246   	340404     	117800     	303691     	1.58134e+06
7  	246   	326176     	28637.4    	238359     	606987     
8  	250   	320459     	99160      	212651     	1.77041e+06
9  	244   	280152     	35823.5    	212651     	525853     
10 	250   	236926     	13575.7    	212651     	306550     
11 	250   	224638     	45695.9    	211954     	683963     
12 	249   	216801     	50138.4    	195494     	976567     
13 	248   	218938     	70215.2    	190553     	1.11576e+06
14 	246   	208675     	43910.9    	144086     	879663     
15 	246   	199225     	77018.3    	144086     	1.32819e+

deap.creator.FitnessMax((100.01361902182661,))

In [ ]:
best[0]

[45.24480783450515, 4.12227571819001, 9.389187570878217, 8.686734715183759]

In [ ]:
betas

array([45.5 ,  3.5 ,  7.8 ,  8.98])

In [ ]:
## Improved solution with simulated annealing


In [ ]:
def search(solution, alpha=0.1):
  return solution  + randn(len(solution)) * alpha


def fitnessFun(chromosome, X, target, df, metric='RMS'):
  yhat =  df.loc[:,X] @  chromosome
  y = df.loc[:,target]
  if metric == 'R':
    return Rsquare(y, yhat)
  else:
    return RMSE(y, yhat)


def boltzmann(deltaE,  T, k=1):
  return exp(-deltaE/(k*T))

In [ ]:
betas_GA= asarray(best[0])

In [ ]:
Ti , Tf = 5, 0
cooling_rate = 20

def SA(solution, search,  Ti, Tf, cooling_rate,  fitnessFunction, seed):
  T = Ti
  while T>Tf:
    for _ in range(cooling_rate):
      solution_temp  = search(solution)
      E0, E1 = fitnessFunction(solution)[0], fitnessFunction(solution_temp)[0]
      if E1 < E0:
        solution = solution_temp
      else:
        if random.uniform(0,1) < boltzmann(E1-E0, T):
          solution = solution_temp
    T = T - 0.1
  return solution

In [ ]:
%%time
betas_GANNE = SA(betas_GA,
    search,
    Ti,
    Tf,
    cooling_rate,
   lambda solution: fitnessFun(solution, X, 'y', df),
   1)

CPU times: user 2.68 s, sys: 28.8 ms, total: 2.71 s
Wall time: 2.91 s


In [ ]:
%%time
# Hor woks only SA
init_sol = toolbox.individual()
betas_SA = SA(init_sol,
    search,
    Ti,
    Tf,
    cooling_rate,
   lambda solution: fitnessFun(solution, X, 'y', df),
   1)

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
mod = ols(formula="y ~ x1 + x2 + x3 + x4 ", data=df)
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.520e+07
Date:                Sun, 05 Nov 2023   Prob (F-statistic):               0.00
Time:                        22:42:47   Log-Likelihood:                -583.10
No. Observations:                 341   AIC:                             1176.
Df Residuals:                     336   BIC:                             1195.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.2124      0.463      0.459      0.6

In [ ]:
betas_OLS = res.params.to_numpy()[1:]

In [ ]:
from sklearn.metrics import r2_score
y_true = df['y']
y_pred = res.predict()
r2_score(y_true, y_pred)

0.9999981417841303

In [ ]:
Rsquare(df['y'], res.predict())

0.9999981417841303

In [ ]:
print('Real:',betas) # Real
print('OLS:',betas_OLS) # Ordinary
print('Genetic:',betas_GA) # Genetic
print('Annealing Genetic:',betas_GANNE) #  Annealing genetic
print('Annealing:',betas_SA) # Annealing

Real: [45.5   3.5   7.8   8.98]
OLS: [45.49919252  3.49933732  7.77931584  8.98149804]
Genetic: [45.24480783  4.12227572  9.38918757  8.68673472]
Annealing Genetic: [45.51804623  3.4858137   7.87844025  8.95215162]
Annealing: [45.3919297   0.8588221  14.99282474  8.61175189]
